config/routes.rb
Rails.application.routes.draw do
  get 'reservations/create'
  devise_for :users
  root to: "spaceships#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :spaceships, only: %i[index show new create edit update] do
    resources :reservations, only: [:create]
  end

  get "dashboard", to: 'reservations#dashboard'
  delete 'spaceships/:id', to: 'spaceships#destroy', as: :spaceship_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :spaceship

  validates :start_date, :end_date, :price, :total_guests, presence: true
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :delete_all
  has_many_attached :photos, dependent: :delete_all

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates :description, presence: true
  validates :capacity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spaceships
  has_many :reservations
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @spaceship = Spaceship.find(params[:spaceship_id])
    @reservation.spaceship = @spaceship

    set_end_price_in_reservation

    if @reservation.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def dashboard
    @spaceships = Spaceship.where("user_id = #{current_user.id}")
    @reservations = Reservation.where("user_id = #{current_user.id}")
    @reservations_all = Reservation.all
    @spaceships_all = Spaceship.all
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :total_guests, :price)
  end

  def set_end_price_in_reservation
    end_of = Date.parse(params[:reservation][:end_date])
    start_of = Date.parse(params[:reservation][:start_date])
    num_of_days = (end_of - start_of).to_i
    @reservation.price = num_of_days * @spaceship.price
  end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = <<~SQL
        spaceships.name ILIKE :query
        OR users.name ILIKE :query
      SQL
      @spaceships = Spaceship.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @spaceships = Spaceship.all
    end
  end

  def show
    @reservation = Reservation.new
    @user = current_user
    @spaceship = Spaceship.find(params[:id])
    # render json: @spaceship
  end

  def new
    @spaceship = Spaceship.new
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    if @spaceship.save
      redirect_to dashboard_path # spaceship_path(@spaceship.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @spaceship = Spaceship.find(params[:id])
  end

  def update
    @spaceship = Spaceship.find(params[:id])
    @spaceship.update(spaceship_params)
    redirect_to spaceship_path(@spaceship)
  end

  def destroy
    @spaceship = Spaceship.find(params[:id])
    @spaceship.destroy
    redirect_to spaceships_path
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :price, :capacity, :description, photos: [])
  end

  # def json_response(object, status = :ok)
  #   render json: object, status: status
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Starbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <div class="wrapper">
      <%= render "shared/navbar" %>
      <div class="background-star">
        <div class="container display-body">
          <%= yield %>
        </div>
        <div>
          <%= render "shared/flashes" %>
        </div>
      </div>
      <%= render "shared/footer" %>
    </div>


    <!-- IMPORTING BOOTSTRAP JS FOR IMAGE CAROUSEL -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<p>hello world</p>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/dashboard.html.erb
<% if @spaceships.empty? && @reservations.empty? %>
  <div class="white-text">
    <h1>No reservations or spaceships.</h1>
  </div>
<% elsif @spaceships.empty? %>
  <div class="white-text">
    <h1> Hello! Here are your reservations: </h1>
  </div>
  <div class="grid-four-col">
    <% @reservations.each do |reservation| %>
      <div class="card-owner">
        <% spaceship = reservation.spaceship %>
        <h5 class="card-title"> <%= spaceship.name %> </h5>
        <div id="card-owner-content-alt">
          <p class="card-owner-text">Booked from <%= reservation.start_date %> until <%= reservation.end_date %> (<%= (reservation.end_date - reservation.start_date).to_i %> nights)</p>
          <p class="card-owner-text">You are paying: $<%= spaceship.price %> </p>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="owner-section">
    <div class="white-text">
      <h1> Here are your spaceships and guest bookings: </h1>
    </div>
    <div class="grid-four-col">
      <% @spaceships.each do |spaceship| %>
        <div class="card-owner">
          <%= link_to "", spaceship_path(spaceship), class: "card-owner-link"%>
          <h5 class="card-title"> <%= spaceship.name %> </h5>
          <% @reservations_all.each do |reservation| %>
            <% if reservation.spaceship_id == spaceship.id %>
              <div id="card-owner-content">
                <p class="card-owner-text"> Guest name: <%= reservation.user.name %> </p>
                <p class="card-owner-text">Booked from <%= reservation.start_date %> until <%= reservation.end_date %> (<%= (reservation.end_date - reservation.start_date).to_i %> nights)</p>
                <p class="card-owner-text"> Your guest is paying: $<%= reservation.price %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="user-section">
    <div class="white-text">
      <h1> Here are your personal bookings: </h1>
    </div>
    <% if @spaceships.empty? == false && @reservations.empty? %>
      <h3>No bookings.</h3>
    <% else %>
      <div class="grid-four-col">
        <% @reservations.each do |reservation| %>
          <div class="card-owner">
            <h5 class="card-title"> <% spaceship = reservation.spaceship %>
            <%= spaceship.name %> </h5>
            <div id="card-owner-content-alt">
              <p class="card-owner-text">Booked from <%= reservation.start_date %> until <%= reservation.end_date %> (<%= (reservation.end_date - reservation.start_date).to_i %> nights)</p>
              <p class="card-owner-text">You are paying: $<%= spaceship.price %> </p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer container">
  <div class="footer-copyright">
    <i class="fas fa-copyright fa-regular"></i>starbnb</div>

  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-expand-sm align-content-md-stretch navbar-light navbar-lewagon">
    <div class=" container container_fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa-solid fa-rocket navbar-logo"></i>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="user-container d-flex">
          <% if user_signed_in? %>
            <%= current_user.name %>
          <% end %>
          <div class="collapse navbar-collapse ms-2" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
                <li class="nav-item dropdown">
                  <%# image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <span class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa-solid fa-user navbar-icon"></i></span>
                   <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
                    <%= link_to "Add Spaceship", new_spaceship_path, class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>



    </div>
  </div>

app/views/spaceships/edit.html.erb
<div class="background-star">
  <div class="container-form display-body">
    <div class="card-create-spaceship">
      <div class="content-create-spaceship">
        <h2>Edit spaceship:</h2>
        <%= simple_form_for(@spaceship) do |f| %>
          <%= f.input :name %>
          <%= f.input :price %>
          <%= f.input :capacity %>
          <%= f.input :description %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.button :submit, class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaceships/index.html.erb
<div class="container display-body">

  <!-- SEARCH-BAR -->
  <div class="search-bar search-hover">
    <%= form_with url: spaceships_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a spaceship"
      %>
      <%= submit_tag "Search", class: "btn btn-primary search-hover" %>
    <% end %>
  </div>

  <!-- CARDS -->
  <div class="grid-four-col">
    <% @spaceships.each do |spaceship| %>
      <div class="card-star">
        <%= link_to "", spaceship_path(spaceship), class: "card-link"%>
        <% if spaceship.photos.present? %>
          <%= cl_image_tag spaceship.photos.first.key, class:"card-img", alt:"Spaceship-img" %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1633984726552-3ed7296dc5c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img" alt="Spaceship-img">
        <% end %>

        <div class="card-content">
          <div class="card-content-upper">
            <h2><%= spaceship.name %></h2>
            <p><i class="fa-solid fa-star fa-xs"></i><%= spaceship.user.name %></p>
          </div>
          <div class="card-content-lower">
            <p><strong>€<%= spaceship.price %></strong> per night</p>
            <p>Capacity: <%= spaceship.capacity %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/spaceships/new.html.erb
<div class="background-star">
  <div class="container-form display-body">
    <div class="card-create-spaceship">
      <div class="content-create-spaceship">
        <h2>Add spaceship:</h2>
        <%= simple_form_for @spaceship do |f| %>
          <%= f.input :name %>
          <%= f.input :price %>
          <%= f.input :capacity %>
          <%= f.input :description %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.button :submit, class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spaceships/show.html.erb
<div class="grid-show">
  <div class="card-spaceship">
    <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="false">

      <% if @spaceship.photos.present? %>
        <div class="carousel-inner">
          <% @spaceship.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= "active" if index == 0 %>">
              <%= cl_image_tag photo.key, class:"card-img d-block w-100", alt:"Spaceship-img" %>
            </div>
          <% end %>
        </div>

        <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      <% else %>
            <img src="https://images.unsplash.com/photo-1633984726552-3ed7296dc5c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" class="card-img" alt="Spaceship-img">
      <% end %>

    </div>

    <div class="card-details">
      <div class="flex-title">
        <h1><%= @spaceship.name %></h1>
        <p><i class="fa-solid fa-star fa-xs"></i><%= @spaceship.user.name %></p>
      </div>
      <div class="card-details-features">
        <p>€<strong><%= @spaceship.price %></strong> per night</p>
        <p>Capacity: <%= @spaceship.capacity %></p>
      </div>
      <p class="card-description"><%= @spaceship.description %></p>
    </div>
  </div>

  <% if @spaceship.user_id == @user.id %>
    <div class="owner-info">
      <h1> This is your spaceship! </h1>
      <div class="show-buttons">
        <%= link_to "Edit", edit_spaceship_path, class: 'btn btn-primary', id: "btn-star" %>
        <%= link_to "Delete", spaceship_destroy_path, class: 'btn btn-primary', id: "btn-star", data: { turbo_method: :delete, turbo_confirm: "Sure?" } %>
      </div>
    </div>
  <% else %>
    <div class="card-form" data-controller="hello">
      <h2 class="form-h2">Reserve this ship:</h2>
      <%= simple_form_for [@spaceship, @reservation] do |f| %>
        <%# <div class="form-inputs" data-action ="keypress->hello#displayTotal"> %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%# input_html: { "data-hello-target" => "content" } %>
        <%= f.input :total_guests %>
        <%# </div> %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
</div>